### ISSUE TITLE
Request Access (Level 1) for 2501babe

### ISSUE THREAD

**Issue by 2501babe** [solana-foundation/solana-improvement-documents#100]
## Requesting Access Level 1 for 2501babe

Discord id: 2501babe

cc @jacobcreech @buffalojoec

**Comment by buffalojoec** [comment]
I vouch for @2501babe

**Comment by jacobcreech** [comment]
@buffalojoec level 1 can't vouch for more level 1s

> Triage
> Requirement: One voucher from anyone with level 2 or above access.

Let's get some more write access on Labs to help out with this situation. I'll vouch for now and close once completed
