### ISSUE TITLE
Request Access (Level 1) for pgarg66

### ISSUE THREAD

**Issue by pgarg66** [solana-foundation/solana-improvement-documents#102]
## Requesting Access Level 1 for pgarg66

Discord id : pgarg

**Comment by pgarg66** [comment]
tag: @jacobcreech, @jeffwashington for vouchers.

**Comment by jeffwashington** [comment]
I vouch for @pgarg66

**Comment by pgarg66** [comment]
tag: @SIMD-Maintainers for vouching completion

**Comment by jacobcreech** [comment]
Invite sent. Closing as completed.
