### ISSUE TITLE
Request Access (Level 2) for pgarg66

### ISSUE THREAD

**Issue by pgarg66** [solana-foundation/solana-improvement-documents#103]
## Requesting Access Level 2 for pgarg66

Discord id: pgarg

**Comment by pgarg66** [comment]
tag: @jeffwashington, @jacobcreech as vouchers.

**Comment by jeffwashington** [comment]
I vouch for @pgarg66

**Comment by jacobcreech** [comment]
Adding an additional vouch and closing as completed
