### ISSUE TITLE
Request Access (Level 1) for sakridge

### ISSUE THREAD

**Issue by sakridge** [solana-foundation/solana-improvement-documents#104]
## Requesting Access Level 1 for sakridge

Discord id is @sakridge

cc @jeffwashington @pgarg66 
Discord id:

**Comment by pgarg66** [comment]
I vouch for @sakridge

**Comment by jeffwashington** [comment]
I vouch for @sakridge

**Comment by jacobcreech** [comment]
Invite sent and closing as completed
