### ISSUE TITLE
Request Access (Level 2) for @t-nelson

### ISSUE THREAD

**Issue by t-nelson** [solana-foundation/solana-improvement-documents#120]
## Requesting Access Level 2 for @t-nelson

Discord id: trent.sol

cc/ @jacobcreech

**Comment by jacobcreech** [comment]
@t-nelson you'll need to request triage access first. Feel free to leave this open to collect vouches+ open a level 1 access issue

**Comment by jacobcreech** [comment]
Vouching and closing as completed
