### ISSUE TITLE
Request Access (Level 2) for CriesofCarrots

### ISSUE THREAD

**Issue by ripatel-fd** [solana-foundation/solana-improvement-documents#136]
## Requesting Access Level 2 for @CriesofCarrots 

Discord id tyera

@CriesofCarrots has authored several feature gates / SIMDs and is a long time contributor.
She should have write access so she can approve, veto, merge others' contributions.

**Comment by CriesofCarrots** [comment]
:salute:

**Comment by buffalojoec** [comment]
I vouch for @CriesofCarrots.

**Comment by jacobcreech** [comment]
Closing as completed
