### ISSUE TITLE
Request Access (Level 2) for joncinque

### ISSUE THREAD

**Issue by joncinque** [solana-foundation/solana-improvement-documents#139]
## Requesting Access Level 2 for joncinque

Discord id: jonc5

Per Jacob's nomination, requesting write access to the SIMD repo for myself

**Comment by buffalojoec** [comment]
I vouch for @joncinque.

**Comment by CriesofCarrots** [comment]
I vouch for @joncinque

**Comment by jacobcreech** [comment]
Closing as completed
