### ISSUE TITLE
Request Access (Level 2) for joncinque

### ISSUE THREAD

**Issue by 0xSol** [solana-foundation/solana-improvement-documents#142]
## Requesting Access Level 2 for @joncinque

@joncinque has authored several feature gates / SIMDs and is a long time contributor who should have write access to review, approve, veto, merge others' contributions.

**Comment by joncinque** [comment]
Thanks for the nom, but this was already done in #139 :smile:

**Comment by jacobcreech** [comment]
As stated, completed in https://github.com/solana-foundation/solana-improvement-documents/issues/139
