### ISSUE TITLE
Request Access (Level 2) for @sakridge

### ISSUE THREAD

**Issue by 0xSol** [solana-foundation/solana-improvement-documents#143]
## Requesting Access Level 2 for @sakridge

@sakridge has authored several feature gates / SIMDs and is a long time contributor who should have write access to review, approve, veto, merge others' contributions.

**Comment by pgarg66** [comment]
I vouch for @sakridge

**Comment by joncinque** [comment]
I vouch for @sakridge

**Comment by jacobcreech** [comment]
Closing as completed
