### ISSUE TITLE
Request Access (Level [1]) for mvines

### ISSUE THREAD

**Issue by mvines** [solana-foundation/solana-improvement-documents#18]
## Requesting Access Level [1] for mvines

Discord id: mvines

**Comment by mvines** [comment]
How do I find out who is level 2 or greater to vouch for moi?

**Comment by jacobcreech** [comment]
> How do I find out who is level 2 or greater to vouch for moi?

I made teams of current people here https://github.com/orgs/solana-foundation/teams.

**Comment by jacobcreech** [comment]
Commenting support for mvines's access

**Comment by jacobcreech** [comment]
Added a wiki page to keep track of everything publicly

https://github.com/solana-foundation/solana-improvement-documents/wiki/SIMD-Member-Access

Closing this since you're now with level 1 access.
