### ISSUE TITLE
Fix filenames for proposals

### ISSUE THREAD

**Issue by brooksprumo** [solana-foundation/solana-improvement-documents#214]
Two proposed SIMDs have inconsistent filenames:
 
* https://github.com/solana-foundation/solana-improvement-documents/blob/main/proposals/simd-0170-builtin-instruction-cost-and-budget.md
* https://github.com/solana-foundation/solana-improvement-documents/blob/main/proposals/simd-0182-conditional-cu-metering.md

Instead, they should be have the "simd-" prefix removed.

**Comment by tao-stones** [comment]
> @tao-stones - tagging you since these are both your SIMDs
> 
Thanks for spotting it, #216 fixes it.
