### ISSUE TITLE
Move over improvement proposals from monorepo

### ISSUE THREAD

**Issue by terorie** [solana-foundation/solana-improvement-documents#3]
**Problem**

The Solana monorepo docs section has two directories containing previous network proposals.
- [proposals](https://github.com/solana-labs/solana/tree/master/docs/src/proposals)
- [implemented-proposals](https://github.com/solana-labs/solana/tree/master/docs/src/implemented-proposals)

Having multiple repos for proposals fragments resources and attention. Would be good to have it all in a single place.

**Suggested Fix**

- Move over documents from monorepo into this repo
- Add SIMD header and assign number
- Preserve original Git authorship attribution

**Comment by mryalamanchi** [comment]
Questions to ask:

Proposals:
  - Numbering of these proposals while retaining the git authorship attribution (Provided suggestion here: [Recommend to choose the issue or pr number for the SIMD-xxxx numbering](https://github.com/ethereum/pm/blob/master/AllCoreDevs-Meetings/Meeting%20129.md)). So, if the suggestion is acceptable for numbering scheme, when the PRs for previous Proposals are created on the SIMD repo, can we stick to the suggested numbering scheme as the PR for these are created?
  
Recommendation:
  - Create a PR and retain authorship for the proposals. The numbering for it is auto-picked by the PR number as per the numbering suggestion mentioned above.
  
  Implemented Proposals:
   - While shifting the Implemented Proposals, do we create the PRs for these or directly assign a number along with a pre-fix to differentiate and avoid any numbering collisions with the current SIMDs?
   - Does the sequence of the already Implemented Proposals matter here while assigning a number?
   
 Recommendation:
   - Assign a prefix, e.g. `pre-SIMD-xxxx` where xxxx is the number picked when the implemented proposals are straight put into the proposals directory
   
   **caution: the numbering scheme itself is a suggestion and not confirmed for now**

**Comment by mryalamanchi** [comment]
Questions to ask:

Proposals:
  - Numbering of these proposals while retaining the git authorship attribution ([Pick the PR number for numbering](https://github.com/solana-foundation/solana-improvement-documents/blob/main/proposals/0001-simd-process.md#draft)). So, when the PRs for previous Proposals are created on the SIMD repo, can we stick to the numbering scheme as the PR for these are created?
  
Recommendation:
  - Create a PR and retain authorship for the proposals. The numbering for it is auto-picked by the PR number as per the numbering scheme mentioned above.
  
  Implemented Proposals:
   - While shifting the Implemented Proposals, do we create the PRs for these or directly assign a number along with a pre-fix to differentiate and avoid any numbering collisions with the current SIMDs?
   - Does the sequence of the already Implemented Proposals matter here while assigning a number?
   
 Recommendation:
   - Assign a prefix, e.g. `pre-SIMD-xxxx` where xxxx is the number picked when the implemented proposals are straight put into the proposals directory

**Comment by nickfrosty** [comment]
I fully agree with @terorie about needing to migrate the older, monorepo based proposals into this new SIMD. And after, removed from the monorepo.

I also agree with @mryalamanchi that they should use a slightly modified naming convention to denote they are the older ones. I support the proposed `pre-SIMD-xxx` scheme, and propose we make the `xxx` number be the PR number from the original monorepo document. It make it simple and to the point. As well as helps to connect back to the original creator of the monorepo proposal.

**Comment by jacobcreech** [comment]
Most proposals on the old repo will likely move to a Labs specific proposal site at some point since so many of them don't apply here.

**Comment by jroy3747** [comment]
Good project
