### ISSUE TITLE
Request Access (Level [1]) for [taozhu-chicago]

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-foundation/solana-improvement-documents#31]
## Requesting Access Level [1] for [taozhu-chicago]

Discord id:Tao#2945

**Comment by mvines** [comment]
Can you please edit the issue text, then I'm happy to vouch if you ping me

**Comment by mvines** [comment]
I vouch for @taozhu-chicago

**Comment by jacobcreech** [comment]
Closing as completed
