### ISSUE TITLE
Request Access (Level [1]) for [jeffwashington]

### ISSUE THREAD

**Issue by jeffwashington** [solana-foundation/solana-improvement-documents#35]
## Requesting Access Level [1] for [jeffwashington]

Discord id:jwash#5045

**Comment by jeffwashington** [comment]
@mvines @criesofcarrots

**Comment by mvines** [comment]
I vouch for @jeffwashington

**Comment by jacobcreech** [comment]
Pending invitation @jeffwashington 
I will close once completed

**Comment by jacobcreech** [comment]
@jeffwashington previous invite expired and I sent another invite
