### ISSUE TITLE
improve access to lint tools

### ISSUE THREAD

**Issue by mschneider** [solana-foundation/solana-improvement-documents#54]
current workflow is not ideal for a globally distributed team.

proposal 1: solana tech discord contributor role should be able to trigger ci / lint run on solana-foundation/solana-improvement-documents
proposal 2: ci just autoruns on every request, as long as PR doesn't touch the ci config, lint tools are pretty lightweight

**Comment by t-nelson** [comment]
> proposal 1: solana tech discord contributor role should be able to trigger ci / lint run on solana-foundation/solana-improvement-documents

imo don't cross the streams. keep discord and github roles on their corresponding platforms

> proposal 2: ci just autoruns on every request, as long as PR doesn't touch the ci config, lint tools are pretty lightweight

The Way :registered:

**Comment by jacobcreech** [comment]
@mvines have you still been approving the runs lately? I updated the settings for actions yesterday when this was brought up.

**Comment by mvines** [comment]
Not today! We'll see if this works when a new contributor sends their first SIMD I guess.

**Comment by jacobcreech** [comment]
Closing as completed. We can reopen if the problem appears again.
