### ISSUE TITLE
Request Access (Level 2) for ripatel-jump

### ISSUE THREAD

**Issue by ripatel-fd** [solana-foundation/solana-improvement-documents#55]
## Requesting Access Level 2 for ripatel-jump

Requesting write access to the SIMD repository on behalf of the Firedancer team.
Firedancer is an effort to implement a second implementation of the Solana protocol.

Contact: ripatel@jumptrading.com

**Comment by mvines** [comment]
I vouch for @ripatel-jump

**Comment by jacobcreech** [comment]
Invited @ripatel-jump given the vouch. Will close this once completed
