### ISSUE TITLE
Question: single slot finality

### ISSUE THREAD

**Issue by blasrodri** [solana-foundation/solana-improvement-documents#78]
I'm interested in having L2s/rollups connected to Solana. Interoperability between these would aim to have latency reduced to the minimum. 

One challenge is time to finality. Is there a plan to move towards a single slot finality model in the future? Or am I missing anything?

Thanks for your time.

**Comment by jacobcreech** [comment]
Hello @blasrodri . Unfortunately this is not the place to ask questions. Please go to the [Solana StackExchange](https://solana.stackexchange.com/) and ask there.
