### ISSUE TITLE
Request Access (Level 1) for buffalojoec

### ISSUE THREAD

**Issue by buffalojoec** [solana-foundation/solana-improvement-documents#92]
## Requesting Access Level 1 for buffalojoe

Discord: buffalojoe

**Comment by buffalojoec** [comment]
@joncinque @Tamgros @jacobcreech

**Comment by jacobcreech** [comment]
@buffalojoec according to simd-7 you need to [obtain level 1 access before level 2](https://github.com/solana-foundation/solana-improvement-documents/blob/main/proposals/0007-access-policy.md#level-2---write-access).

> Applicants must have level 1 access to apply for level 2.

**Comment by buffalojoec** [comment]
@jacobcreech any other items remaining here?

**Comment by jacobcreech** [comment]
@buffalojoec technically needs a vouch from someone to gain access. I'll give it in this case as we ramp up access for everyone that needs it

**Comment by jacobcreech** [comment]
Closing as completed
